### ISSUE TITLE
ModuleNotFoundError: No module named 'speexdsp_ns'

### ISSUE THREAD

**Issue by dzianisv** [dscripka/openWakeWord#106]
Module fails on macOS because `ModuleNotFoundError: No module named 'speexdsp_ns'`

```shell
Traceback (most recent call last):
  File "/Users/engineer/workspace/AssistantPlato/./src/wakeword.py", line 31, in <module>
    wait_for_wakeup_word()
  File "/Users/engineer/workspace/AssistantPlato/./src/wakeword.py", line 17, in wait_for_wakeup_word
    oww_model = Model(enable_speex_noise_suppression=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/engineer/workspace/AssistantPlato/.venv/lib/python3.11/site-packages/openwakeword/utils.py", line 539, in wrapped
    return func(*args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/engineer/workspace/AssistantPlato/.venv/lib/python3.11/site-packages/openwakeword/model.py", line 202, in __init__
    from speexdsp_ns import NoiseSuppression
ModuleNotFoundError: No module named 'speexdsp_ns'
```

**Comment by dzianisv** [comment]
ok, it seems that this module depends on speexdsp-lib that is not available for macOS

**Comment by dscripka** [comment]
That's correct, that library would need to be compiled for OSX. But the functionality provided by that library is optional, so I can adjust `setup.py` so that you won't get that error when install on Mac systems.

**Comment by JIeJaitt** [comment]
> That's correct, that library would need to be compiled for OSX. But the functionality provided by that library is optional, so I can adjust `setup.py` so that you won't get that error when install on Mac systems.
hi～Can arm's Apple chip mac run this project?
