### ISSUE TITLE
train_custom_verifier not iterating over positive_reference_clips

### ISSUE THREAD

**Issue by mikejgray** [dscripka/openWakeWord#160]
```
❯ poetry run python scripts/train_custom_verifier.py
Configuration file exists at /Users/Mike/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/Mike/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
WARNING:root:Tried to import the tflite runtime, but it was not found. Trying to switching to onnxruntime instead, if appropriate models are available.
Processing positive reference clips:   0%|                                                                              | 0/55 [00:00<?, ?it/s]/
Traceback (most recent call last):
  File "/Users/Mike/Documents/coding/VoiceAssistants/ovos-mac/scripts/train_custom_verifier.py", line 3, in <module>
    openwakeword.train_custom_verifier(
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.10/lib/python3.10/site-packages/openwakeword/custom_verifier_model.py", line 152, in train_custom_verifier
    [get_reference_clip_features(i, oww, model_name, N=5)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.10/lib/python3.10/site-packages/openwakeword/custom_verifier_model.py", line 152, in <listcomp>
    [get_reference_clip_features(i, oww, model_name, N=5)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.10/lib/python3.10/site-packages/openwakeword/custom_verifier_model.py", line 65, in get_reference_clip_features
    sr, dat = scipy.io.wavfile.read(reference_clip)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.10/lib/python3.10/site-packages/scipy/io/wavfile.py", line 647, in read
    fid = open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/'
Processing positive reference clips:   0%|  
```

It looks like at some point `custom_verifier_clips` was converted from a list to a string, [but there wasn't code added to iterate over the path](https://github.com/dscripka/openWakeWord/blob/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb/openwakeword/custom_verifier_model.py#L152).

**Comment by mikejgray** [comment]
After a lot of experimentation it seems that while the type hint is `str`, it actually still wants a list of individual files and not a filepath. If I do that, the model trains successfully on both Linux and Mac OS. I'm planning to submit a PR to address the type hints and docstrings 🙂
