### ISSUE TITLE
Gpu usage for Rnn Training

### ISSUE THREAD

**Issue by thatsri9ht** [dscripka/openWakeWord#172]
With a NVIDIA GeForce RTX 3070 GPU and 16 GB of RAM on my PC, When training my LSTM model on the GPU, I encountered a CUDA out-of-memory error, indicating insufficient GPU memory to allocate tensors. I've tried reducing the batch size and simplifying the model architecture, but the issue persists. Any suggestions or guidance on how to address this problem would be greatly appreciated!

torchvision is not available - cannot save figures
INFO:root:##################################################
Starting training sequence 1...
##################################################
Training:  75%|█████████████████████       | 3750/5000 [00:12<00:04, 310.02it/s]
Traceback (most recent call last):
  File "/home/thatsri9ht/python/openwakeword/openwakeword/train.py", line 888, in <module>
    best_model = oww.auto_train(
  File "/home/thatsri9ht/python/openwakeword/openwakeword/train.py", line 276, in auto_train
    self.train_model(
  File "/home/thatsri9ht/python/openwakeword/openwakeword/train.py", line 519, in train_model
    val_predictions = self.model(x_val)
  File "/home/thatsri9ht/anaconda3/envs/openwakeword/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/thatsri9ht/anaconda3/envs/openwakeword/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/thatsri9ht/python/openwakeword/openwakeword/train.py", line 94, in forward
    out, h = self.layer1(x)
  File "/home/thatsri9ht/anaconda3/envs/openwakeword/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/thatsri9ht/anaconda3/envs/openwakeword/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/thatsri9ht/anaconda3/envs/openwakeword/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 888, in forward
    c_zeros = torch.zeros(self.num_layers * num_directions,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 472.00 MiB. GPU

**Comment by EthanEpp** [comment]
Are you using your own feature embedding npys, or the provided ones?

**Comment by thatsri9ht** [comment]
I use both my own features and the features of 2000 hours available in huggingface

**Comment by EthanEpp** [comment]
I see, I believe the issue comes from line of the train function: https://github.com/dscripka/openWakeWord/blob/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb/openwakeword/train.py#L868 as it is  compatible with the false positive validation set features also from the huggingface, but it ends up loading the entire false validation feature set into memory in order to reshape it so memory runs out. If your features are already the same shape as the model, (n, 16, 96) i believe, you can just comment out this line and it should work. I am working on a more robust fix that can do the resizing and will hopefully have a PR up for that in the next day or so.

**Comment by dscripka** [comment]
@EthanEpp is correct, the script currently loads the validation data into memory as it generally is small enough to not cause an issues. Training RNN based models can dramatically increase the memory requirements for training (at least in comparison to the default simple DNN modles), so in this case you may need to make modifications to `train.py`.

If it helps, from my testing RNN based models only rarely perform better than DNN models for short wake words.

**Comment by Joseph513shen** [comment]
Hello, when I want to train the code through train.py, I found that there is no "generate_samples" function. Have you encountered this problem?thx
