### ISSUE TITLE
ValueError: mmap length is greater than file size

### ISSUE THREAD

**Issue by maciejmajek** [dscripka/openWakeWord#198]
When running the automatic_model_training.ipynb locally, I've come across a problem with the training script --train_model.
I was able to solve this by adding + to the mmap_mode.
```python
self.data = {label: np.load(fl, mmap_mode='r+') for label, fl in data_files.items()}
```

env:
python3.10

<details><summary>Stack trace</summary>
<p>

File "openwakeword/openwakeword/train.py", line 845, in <module>
    batch_generator = mmap_batch_generator(
  File "/home/mmajek/projects/internal/rai/openwakeword/openwakeword/data.py", line 788, in __init__
    self.data = {label: np.load(fl, mmap_mode='r') for label, fl in data_files.items()}
  File "/home/mmajek/projects/internal/rai/openwakeword/openwakeword/data.py", line 788, in <dictcomp>
    self.data = {label: np.load(fl, mmap_mode='r') for label, fl in data_files.items()}
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-qH6Oly3A-py3.10/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-qH6Oly3A-py3.10/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-qH6Oly3A-py3.10/lib/python3.10/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size

</p>
</details>

**Comment by adgud** [comment]
Hey, this fixed this error for me too, however I encounter another one right after that:

```
/mnt/openWakeWord/venv/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "/mnt/openWakeWord/notebooks/openwakeword/openwakeword/train.py", line 867, in <module>
    X_val_fp = np.load(config["false_positive_validation_data_path"])
  File "/mnt/openWakeWord/venv/lib/python3.10/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

Did you manage to work around after that one?

**Comment by maciejmajek** [comment]
Looks like numpy changed the default behavior of np.load in 1.16 version. In [1.15](https://numpy.org/doc/1.15/reference/generated/numpy.load.html) it's still `allow_pickle==True` by default. I'd suggest either downgrading np version (which might create conflicts) or directly adding `allow_pickle=True` in `np.load(config["false_positive_validation_data_path"])`

**Comment by adgud** [comment]
Sadly, downgrading numpy is not possible as other packages (like `acoustics==0.2.6`) requires numpy >= 1.18.

Adding `allow_pickle=True` is something I tried already, but it leads to a different error:

```
/mnt/openWakeWord/venv/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "/mnt/openWakeWord/venv/lib/python3.10/site-packages/numpy/lib/npyio.py", line 441, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/openWakeWord/notebooks/openwakeword/openwakeword/train.py", line 868, in <module>
    X_val_fp = np.load(config["false_positive_validation_data_path"],allow_pickle=True)
  File "/mnt/openWakeWord/venv/lib/python3.10/site-packages/numpy/lib/npyio.py", line 443, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file 'validation_set_features.npy' as a pickle
```

**Comment by maciejmajek** [comment]
Looks like you are in a pickle 🤷‍♂ :D. No idea, seems like the project is getting stale.
